-- Migrate the existing `urls` table to a HASH-partitioned table.
--
-- Postgres cannot turn a plain table into a partitioned one in place, so the
-- migration builds a new partitioned `urls` alongside the old data and copies
-- the rows across. Partitioning is on `short_code` (HASH) because every public
-- lookup is by short code, and a unique/PK on a partitioned table MUST include
-- the partition key — `short_code` already carries the uniqueness the collision
-- logic depends on, so it is the natural partition key.

-- 1. Set the old table aside so the new partitioned `urls` can take its name.
--    Rename its PK constraint and unique index too, so the new table can reuse
--    the original names (`urls_pkey`, `urls_short_code_key`).
ALTER TABLE "urls" RENAME TO "urls_legacy";
ALTER TABLE "urls_legacy" RENAME CONSTRAINT "urls_pkey" TO "urls_legacy_pkey";
ALTER INDEX "urls_short_code_key" RENAME TO "urls_legacy_short_code_key";

-- 2. Create the partitioned parent. The PK is the composite (id, short_code):
--    HASH partitioning requires the partition key (short_code) in every
--    unique/PK, so `id` alone can no longer be the primary key. `id` stays an
--    auto-incrementing identity column, so the model keeps `Int @default(autoincrement())`.
CREATE TABLE "urls" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "short_code" TEXT NOT NULL,
    "original_url" TEXT NOT NULL,
    "clicks" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "urls_pkey" PRIMARY KEY ("id", "short_code")
) PARTITION BY HASH ("short_code");

-- 3. Create the four hash partitions. Postgres routes each row to a partition by
--    hashing short_code modulo 4 — lookups by short_code prune to one partition.
CREATE TABLE "urls_p0" PARTITION OF "urls" FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE "urls_p1" PARTITION OF "urls" FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE "urls_p2" PARTITION OF "urls" FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE "urls_p3" PARTITION OF "urls" FOR VALUES WITH (MODULUS 4, REMAINDER 3);

-- 4. The unique index on short_code spans all partitions. short_code is the
--    partition key, so this global UNIQUE is legal and keeps codes unique across
--    the whole table — exactly what the collision retry relies on.
CREATE UNIQUE INDEX "urls_short_code_key" ON "urls" ("short_code");

-- 5. Copy existing rows across, preserving their ids (OVERRIDING SYSTEM VALUE
--    writes the migrated id into the identity column).
INSERT INTO "urls" ("id", "short_code", "original_url", "clicks", "created_at")
OVERRIDING SYSTEM VALUE
SELECT "id", "short_code", "original_url", "clicks", "created_at" FROM "urls_legacy";

-- 6. Advance the identity sequence past the largest copied id so new inserts do
--    not collide with migrated rows.
SELECT setval(
    pg_get_serial_sequence('"urls"', 'id'),
    GREATEST((SELECT COALESCE(MAX("id"), 0) FROM "urls"), 1)
);

-- 7. Drop the old table now that its rows live in the partitioned one.
DROP TABLE "urls_legacy";
